# All intervals are in ticks (20 ticks = 1 second)
BalanceTopTimerInterval: 1200

currencyNameSingular: "Satoshi"
currencyNamePlural: "Sats"
startingBalance: 100
# Changing the locale will change wht format the money is in, see 
# https://www.techonthenet.com/js/language_tags.php for examples.
locale: "en-US"
# Note: The custom symbol may not work if minecraft doesn't allow that symbol.
#       The custom symbol may need to be in unicode format (e.g. \u26C3 for 
#       dollar sign) to be able to work.
customSymbolEnabled: false
customSymbol: ""

lnbits:
  #UUID of wallet to provide liquidity or a "Float"
  ServerUUID: ""
  #AdminKey of Admin wallet
  AdminKey:
  #Apikey from usermanager user
  APIKey:
  #Admin User for main wallet
  AdminUser:
  #usernamager User ID
  UserID:
  #Usermanager User name
  UserName:
  #LNBits server DNS or IP
  server:
  #LNBits port
  port:

suffixes:
  # amount is multiplied by 10^number.
  # e.g. for k, the amount is multiplied by 10^3 (1,000)
  k: 3
  K: 3
  BTC: 8
  Bitcoin: 8

