# General settings
BalanceTopTimerInterval: 1200
currencyNameSingular: "Satoshi"
currencyNamePlural: "Sats"
startingBalance: 100
customSymbol: "⚡"

ServerUUID: ""
TOSURL: ""
lnaddr: true
DEBUG: true

# LNBits Server settings
host: ""
pubhost: ""
port: 5000

# Bearer tokens - "blahblahblahblahblahblahblahblahblah"
BearerTokens:
  default: "<default-bearer-token>"    # Fallback token if a specific one isn't defined
  wallets: null    # Optional, overrides default
  users: null
  payments: null
  extension: null
  currencies: null
  conversion: null
  lnurlscan: null
  wallet: null

  suffixes:
  # amount is multiplied by 10^number.
  # e.g. for k, the amount is multiplied by 10^3 (1,000)
  k: 3
  K: 3
  BTC: 8
  Bitcoin: 8