# General settings
BalanceTopTimerInterval: 1200
currencyNameSingular: "Satoshi"
currencyNamePlural: "Sats"
startingBalance: 100
customSymbol: "⚡"

ServerUUID: ""
TOSURL: ""
lnaddr: true
DEBUG: true

# LNBits Server settings
host: ""
pubhost: ""
port: 5000

# Bearer tokens - "blahblahblahblahblahblahblahblahblah"
BearerTokens:
  default: "<default-bearer-token>"    # Fallback token if a specific one isn't defined
  wallets: null    # Optional, overrides default
  users: null
  payments: null
  extension: null
  currencies: null
  conversion: null
  lnurlscan: null
  wallet: null