name: Sovereign-Craft-Economy
version: 1.0
main: com.sovereigncraft.economy.SCEconomy
api-version: 1.19
depend: [Vault]
load: STARTUP
author: Sovtoshi
description: Bitcoin Lightning Economy for Minecraft
website: SovereignCraft.com
commands:
  pay:
    description: Send some money to another player
    aliases: [send, tip]
    usage: /pay <player> <amount>
  balance:
    description: Get your balance
    aliases: [bal]
  webwallet:
    description: Opens a webpage with your lightning wallet
  donate:
    description: Sends a donation to the server operations team. Thank You!
  deposit:
    description: Deposit Lightning with a QR code in game
  acceptTOS:
    description: Creates a new Lighting wallet if one does not exist. Please read TOS first.
  refreshwallet:
    description: regenerates wallet in case it was compromised
