name: SovereignCraftEconomy
version: 1.0.11
main: com.sovereigncraft.economy.SCE
api-version: 1.19
load: STARTUP
depend: [Vault]
author: Sovtoshi & Cappy_SC
description: Bitcoin Lightning Economy for Minecraft
website: https://SovereignCraft.com

commands:
  wallet:
    description: View all your LNBits Lightning wallets and their balances.
    usage: /wallet
