name: Sovereign-Craft-Economy
version: 1.0
main: com.sovereigncraft.economy.SCEconomy
api-version: 1.19
depend: [Vault]
load: STARTUP
authors: [ Sovtoshi ]
description: Bitcoin Lightning Economy for Minecraft
website: SovereignCraft.com
commands:
  pay:
  balance:
    aliases: [bal]
  webwallet:
  donate:
  acceptTOS:
