name: SovereignCraftEconomy
version: 1.0.13
main: com.sovereigncraft.economy.SCE
api-version: 1.19
load: STARTUP
author: Sovtoshi & Cappy_SC
description: Bitcoin Lightning Economy for Minecraft
website: https://SovereignCraft.com

commands:
  wallet:
    description: View all your LNBits Lightning wallets and their balances.
    usage: /wallet
  balance:
    description: Display the balance of your primary Lightning wallet.
    usage: /balance
